# Generated by Django 4.2.2 on 2023-06-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_name', models.CharField(max_length=100)),
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pname', models.CharField(max_length=100)),
                ('Pid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
